myApp:
    prefix: /api/v1-Hg8E39Jol1
    routes:
        - name: application
          path: /monitoring-export
          defaults:
              handler: GeorgRinger\Ieb\Controller\Api\MonitoringExportApi
