services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  GeorgRinger\Ieb\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'


  GeorgRinger\Ieb\Service\CustomDataHandler:
    public: true

  GeorgRinger\Ieb\Command\FristUeberwachungCommand:
    tags:
      - name: 'console.command'
        command: 'ieb:fristUeberwachung'
        description: 'Send mails for fristen'