services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  GeorgRinger\Ieb\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'


  GeorgRinger\Ieb\Service\CustomDataHandler:
    public: true

  GeorgRinger\Ieb\Service\MailService:
    public: true

  GeorgRinger\Ieb\Command\FristUeberwachungCommand:
    tags:
      - name: 'console.command'
        command: 'ieb:fristUeberwachung'
        description: 'Send mails for fristen'
  GeorgRinger\Ieb\Command\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'ieb:import'
        description: 'Import data from old system'

  # Events
  GeorgRinger\Ieb\EventListener\AnsuchenEinreichenListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/ansuchen-einreichen'
        event: GeorgRinger\Ieb\Event\AnsuchenEinreichenEvent

  GeorgRinger\Ieb\EventListener\AnsuchenBegutachtungFinalizeListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/ansuchen-begutachtung-finalize'
        event: GeorgRinger\Ieb\Event\AnsuchenBegutachtungFinalizeEvent

  GeorgRinger\Ieb\EventListener\AnsuchenPdfGenerationListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/ansuchen-begutachtung-pdfgeneration'
        event: GeorgRinger\Ieb\Event\AnsuchenBegutachtungFinalizeAfterSnapshotEvent

  GeorgRinger\Ieb\EventListener\AnsuchenBegutachtungsSchlussListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/ansuchen-begutachtungs-schluss'
        event: GeorgRinger\Ieb\Event\AnsuchenBegutachtungsSchlussEvent

  GeorgRinger\Ieb\EventListener\AnsuchenZuteilungListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/ansuchen-zuteilung'
        event: GeorgRinger\Ieb\Event\AnsuchenZuteilungEvent

  GeorgRinger\Ieb\EventListener\ArchiveActionListener:
    tags:
      - name: event.listener
        identifier: 'ext-ieb/archive-angebotverantwortlicher'
        event: GeorgRinger\Ieb\Event\AngebotVerantwortlichArchiveEvent
        method: 'archiveAngebotVerantwortlich'
      - name: event.listener
        identifier: 'ext-ieb/archive-berater'
        event: GeorgRinger\Ieb\Event\BeraterArchiveEvent
        method: 'archiveBerater'
      - name: event.listener
        identifier: 'ext-ieb/archive-trainer'
        event: GeorgRinger\Ieb\Event\TrainerArchiveEvent
        method: 'archiveTrainer'
