services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false


  GeorgRinger\Ieb\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'


  GeorgRinger\Ieb\Service\CustomDataHandler:
    public: true
