styles:
  content:
    textmedia:
      linkWrap:
        width: 2800m
        height: 1200m
        lightboxEnabled: 1
        lightboxCssClass: fancybox
        lightboxRelAttribute: fancybox-{field:uid}
      maxW: 2800
      maxWInText: 1000
    image:
      linkWrap:
        lightboxEnabled: 1
        lightboxCssClass: fancybox
        lightboxRelAttribute: fancybox-{field:uid}

page:

  meta:
    viewport: 'width=device-width, initial-scale=1'
    robots: 'index,follow'
    apple-mobile-web-app-capable: 'no'
    compatible: 'IE=edge'

  tracking:
    google:
      trackingID: ''
      anonymizeIp: '1'

config:
  no_cache: '1'
  removeDefaultJS: '0'
  admPanel: '1'
  prefixLocalAnchors: 'all'
  headerComment: 'Eine Website von mangomoon.at'
  sendCacheHeaders: '1'

