base: 'https://901414.jweiland-hosting.de/'
baseVariants:
  -
    base: 'https://akkreditierung2026.ddev.site/'
    condition: 'applicationContext == "Development/Ddev"'
dependencies:
  - mangomoon/mangomoon
  - mangomoon/mangomoonspecify
  - typo3/felogin
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
  -
    errorCode: 403
    errorHandler: PHP
    errorPhpClassFQCN: Plan2net\Sierrha\Error\StatusForbiddenHandler
    tx_sierrha_loginPage: 't3://page?uid=9'
    tx_sierrha_loginUrlParameter: 'return_url=###URL###'
    tx_sierrha_noPermissionsContentSource: ''
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_AT.utf8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-at
    direction: ltr
    flag: at
    websiteTitle: ''
rootPageId: 1
sitePackage: ''
websiteTitle: AKDB
