base: 'https://901414.jweiland-hosting.de/'
baseVariants:
  -
    base: 'https://ieb.ddev.site/'
    condition: 'applicationContext == "Development/Ddev"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_AT.utf8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-at
    direction: ltr
    flag: at
    websiteTitle: ''
rootPageId: 1
websiteTitle: ''
